### PR TITLE
style(clang-tidy): fix bugprone-return-const-ref-from-parameter errors

### LINKED ISSUE #1657: ClangTidy warnings for `bugprone-return-const-ref-from-parameter`
```
/Users/jviotti/Projects/core/src/core/jsonpointer/jsonpointer.cc:142:12: error: returning a constant reference parameter may cause use-after-free when the parameter is constructed from a temporary [bugprone-return-const-ref-from-parameter,-warnings-as-errors]
  142 |     return document;
      |            ^~~~~~~~

/Users/jviotti/Projects/core/src/core/jsonpointer/jsonpointer.cc:150:12: error: returning a constant reference parameter may cause use-after-free when the parameter is constructed from a temporary [bugprone-return-const-ref-from-parameter,-warnings-as-errors]
  150 |     return document;
      |            ^~~~~~~~

```

### PR DESCRIPTION
**Pull request by bavulapati**
fixes #1657

### CODE REVIEW

File: src/core/jsonpointer/jsonpointer.cc [hunk 1]
```diff
@@ -137,15 +137,17 @@ auto try_traverse(const sourcemeta::core::JSON &document,
 
 namespace sourcemeta::core {
 
-auto get(const JSON &document, const Pointer &pointer) -> const JSON & {
+auto get(const JSON &document [[clang::lifetimebound]], const Pointer &pointer)
```
Comment (bavulapati) [inline src/core/jsonpointer/jsonpointer.cc:140]: This seem to be clang specific

File: src/core/jsonpointer/include/sourcemeta/core/jsonpointer.h [hunk 2]
```diff
@@ -52,6 +52,12 @@ const WeakPointer empty_weak_pointer;
 /// A JSON Pointer with unresolved wildcards
 using PointerTemplate = GenericPointerTemplate<Pointer>;
 
+// overloaded functions
+auto get(const JSON &&document, const Pointer &pointer)
```
Comment (jviotti) [inline src/core/jsonpointer/include/sourcemeta/core/jsonpointer.h:56]: Also, could this be like this:

```suggestion
auto get(JSON &&document, const Pointer &pointer)
```

Comment (bavulapati) [reply src/core/jsonpointer/include/sourcemeta/core/jsonpointer.h:56]: I don't think so, because the check talks about returning const ref parameter as const ref.
I will try to test it though

File: src/core/jsonpointer/include/sourcemeta/core/jsonpointer.h [hunk 3]
```diff
@@ -98,6 +108,16 @@ auto get(const JSON &document, const Pointer &pointer) -> const JSON &;
 SOURCEMETA_CORE_JSONPOINTER_EXPORT
 auto get(const JSON &document, const WeakPointer &pointer) -> const JSON &;
 
+// overloaded function
```
Comment (jviotti) [inline src/core/jsonpointer/include/sourcemeta/core/jsonpointer.h:111]:
```suggestion
```

**Review by jviotti — APPROVED** [review]

**Comment by jviotti** [comment]
I just removed the `overloaded function` comments (as that's implicit), but otherwise looks good. Thanks!
